apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-__ENV__-canary
  labels:
    app: backend
    env: __ENV__
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      env: __ENV__
      track: canary
  template:
    metadata:
      labels:
        app: backend
        env: __ENV__
        track: canary
    spec:
      containers:
        - name: backend
          image: aljazkni/simplefortunecookie-backend:__IMAGE_TAG__
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: config-__ENV__
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10