apiVersion: v1
kind: Service
metadata:
  name: frontend-__ENV__
spec:
  type: NodePort
  selector:
    app: frontend
    env: __ENV__
    expose: "true"
  ports:
    - port: 8080
      targetPort: 8080
