apiVersion: v1
kind: Service
metadata:
  name: frontend-__ENV__
spec:
  type: LoadBalancer
  selector:
    app: frontend
    env: __ENV__
    track: stable
  ports:
    - port: 8080
      targetPort: 8080