apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-__ENV__
  labels:
    app: redis
    env: __ENV__
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis
      env: __ENV__
  template:
    metadata:
      labels:
        app: redis
        env: __ENV__
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-__ENV__